version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: gogameserver_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gogameserver
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: gogameserver_redis
    restart: unless-stopped
    command: redis-server --requirepass "password"
    environment:
      REDIS_PASSWORD: password
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
