definitions:
  commands.JoinRoomCommand:
    properties:
      name:
        type: string
      player_id:
        type: string
      room_id:
        type: string
      user_id:
        type: string
    required:
    - name
    - room_id
    type: object
  commands.PlayerCreateRoomCommand:
    properties:
      name:
        type: string
      user_id:
        type: string
    required:
    - name
    type: object
  dtos.PlayerDTO:
    properties:
      created_at:
        type: string
      id:
        type: string
      name:
        type: string
      updated_at:
        type: string
      user_id:
        type: string
    type: object
  dtos.RoomDTO:
    properties:
      created_at:
        type: string
      id:
        type: string
      status:
        type: string
      updated_at:
        type: string
    type: object
  dtos.RoomPlayerDTO:
    properties:
      disconnected_at:
        type: string
      is_disconnected:
        type: boolean
      is_host:
        type: boolean
      is_ready:
        type: boolean
      player:
        $ref: '#/definitions/dtos.PlayerDTO'
      player_id:
        type: string
      room:
        $ref: '#/definitions/dtos.RoomDTO'
      room_id:
        type: string
    type: object
  player_room_cmd.UpdateRoomPlayerCommand:
    properties:
      disconnected_at:
        type: string
      is_disconnected:
        type: boolean
      is_host:
        type: boolean
      is_ready:
        type: boolean
    type: object
info:
  contact: {}
paths:
  /api/v1/room/{room_id}/players/{player_id}:
    delete:
      consumes:
      - application/json
      description: Removes a player from the specified room.
      parameters:
      - description: Room ID (UUID)
        in: path
        name: room_id
        required: true
        type: string
      - description: Player ID (UUID)
        in: path
        name: player_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            type: boolean
        "400":
          description: bad request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Kick a player from a room
      tags:
      - Room.Players
    put:
      consumes:
      - application/json
      description: Partially updates the information of a player in a room.
      parameters:
      - description: Room ID (UUID)
        in: path
        name: room_id
        required: true
        type: string
      - description: Player ID (UUID)
        in: path
        name: player_id
        required: true
        type: string
      - description: Fields to update
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/player_room_cmd.UpdateRoomPlayerCommand'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.RoomPlayerDTO'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update a player in a room
      tags:
      - Room.Players
  /api/v1/room/player/create:
    post:
      consumes:
      - application/json
      description: Allows a player to create a new room with a name and user ID
      parameters:
      - description: Player Create Room Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/commands.PlayerCreateRoomCommand'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.RoomPlayerDTO'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Player creates a new room
      tags:
      - Room.Player
  /api/v1/room/player/join:
    post:
      consumes:
      - application/json
      description: Allows a player to join an existing room with a name, user ID,
      parameters:
      - description: Player Join Room
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/commands.JoinRoomCommand'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.RoomPlayerDTO'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Player joins a room
      tags:
      - Room.Player
swagger: "2.0"
